# Generated by Django 3.2.15 on 2022-10-13 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221013_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uid',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
