# Generated by Django 3.2.15 on 2022-10-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20221013_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
    ]
